language: python
python:
  - "3.2"
jdk:
  - oraclejdk7
env:
 global:
  - "ARTIFACTS_AWS_REGION=eu-west-1"
  - "ARTIFACTS_S3_BUCKET=ingress-apk-mod"
  - secure: "h0SC1XVz6I/MycOqd36mdyhMGqk1AFsMLCP5dU+phm+WhPOq+RCs8fmUq3R1nsnppjn0EuqsBq+dP4CLtVrVc5npuGCmSHrw7a/jti1bHZWXPRxI2rmnZa2r/TzhyzfEDjKcbS7PbPr6iFDMYiqSfT3Mz/X5ooBuiP3ZsIhx4OU="
  - secure: "NbeuXbxFhjE1m/9uMy2c96XY6UXEHa9SvgjDw9Ybc6BiRWvYQwhEyZpPMYvteyp3ZhFxHOskkEFhX2oYMr7B7Saab8tp551ylteoEnqGk3r6t/hKn/H/k/K0RLiZJ6CkzVxmyWnIkTcC5QBCYaTJ4Z2/Zg9s1jBY4aWbLrtEbNk="
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
  - tar -zxf android-sdk-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/17.0.0/:${ANDROID_HOME}/tools/proguard/bin/
  - echo y | android update sdk --filter android-17,platform-tools,build-tools-17.0.0 --all --no-ui --force
  - wget http://dekanszn.ru/lib.tar.gz
  - tar xvfz lib.tar.gz
  - wget http://dekanszn.ru/ingress-latest.apk
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - "gem install travis-artifacts"
script:
  - git config --global user.email ""
  - git config --global user.name "Ingress apk mod"
  - python bin/import_apk.py ingress-latest.apk
  - python bin/release.py
after_success:
  - "travis-artifacts upload --path ingress-latest-broot-*.apk --target-path builds" 
  - "travis-artifacts upload --path ingress-latest-broot-*-mute.apk --target-path builds"
branches:
  only:
    - master
notifications:
  email: false
